# Setup
title:               JXNVCE ALGO-LOG
tagline:             'YouJin Jung'
description:         'Archive of Janice Algorithm Practices'
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              YouJin Jung
  url:               https://github.com/jung-youjin
  email:             jungyoujin0527@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.0.0
google_analytics_id: 277822921
